---
title: "Inläsning av valresultat"
author: "Richard Öhrvall"
format: html
---

# Inläsning av valresultat
Kod för att läsa in valresultat från Valmyndigheten avseende 2026.

```{r}
library(tidyverse)
library(jsonlite)
library(janitor)

```

```{r}
# Genrepsfiler för val 2026
index_url <- "https://resultat.val.se/resultatfiler/genrep2026/index.md5"

index <- readLines(index_url, encoding = "UTF-8")

head(index, 20)

grep("RD", index, value = TRUE)
```


```{r}
base_url <- "https://resultat.val.se/resultatfiler/genrep2026"

rd_url <- paste0(
  base_url,
  "/p/rd/Genrep_2026_preliminar_00_RD.zip"
)

rd_zip <- tempfile(fileext = ".zip")

download.file(rd_url, rd_zip, mode = "wb")

unzip(rd_zip, list = TRUE)


```

```{r}
rd_dir <- tempfile()
dir.create(rd_dir)

rd_file <- "Genrep_2026_preliminar_rostfordelning_00_RD.json"

unzip(
  rd_zip,
  files = rd_file,
  exdir = rd_dir
)

rd_raw <- fromJSON(
  file.path(rd_dir, rd_file),
  simplifyVector = FALSE
)

names(rd_raw)
str(rd_raw, max.level = 2)

```

```{r}
names(rd_raw$valdistrikt[[1]])

str(rd_raw$valdistrikt[[1]], max.level = 3)

rd_raw$valdistrikt[[1]]$namn
```


```{r}
names(rd_raw$valdistrikt[[1]]$rostfordelning)
str(
  rd_raw$valdistrikt[[1]]$rostfordelning,
  max.level = 4
)
```


```{r}
names(
  rd_raw$valdistrikt[[1]]$rostfordelning$rosterPaverkaMandat
)

names(
  rd_raw$valdistrikt[[1]]$rostfordelning$rosterPaverkaMandat$partiRoster[[1]]
)

names(
  rd_raw$valdistrikt[[1]]$rostfordelning$rosterEjPaverkaMandat
)
```

```{r}

i <- which(
  map_chr(rd_raw$valdistrikt, "valdistriktstyp") == "valdistrikt" &
  map_chr(rd_raw$valdistrikt, "statusJamforelse") == "Kan jämföras"
)[1]

vd <- rd_raw$valdistrikt[[i]]

vd$namn

partier <- vd$rostfordelning$rosterPaverkaMandat$partiRoster |>
  map_dfr(as_tibble) |>
  clean_names()

partier


ovriga_raw <- vd$rostfordelning$rosterPaverkaMandat$rosterOvrigaPartier

ovriga <- tibble(
  partibeteckning = "Övriga partier",
  partiforkortning = NA_character_,
  partikod = NA_character_,
  fargkod = NA_character_,
  ordningsnummer = NA_integer_,
  antal_roster = ovriga_raw$antalRoster,
  andel_roster = ovriga_raw$andelRoster,
  antal_roster_foregaende_val = ovriga_raw$antalRosterForegaendeVal,
  andel_roster_foregaende_val = ovriga_raw$andelRosterForegaendeVal,
  forandring_antal_roster = ovriga_raw$forandringAntalRoster,
  forandring_andel_roster = ovriga_raw$forandringAndelRoster,
  partityp = "ovriga_partier"
)

partier <- partier |>
  mutate(partityp = "parti") |>
  bind_rows(ovriga)

partier

```


```{r}
valresultat_test <- partier |>
  rename(radtyp = partityp) |>
  mutate(
    valtillfalle = rd_raw$valtillfalle,
    valklass = rd_raw$valklass,
    rakningstillfalle = rd_raw$rakningstillfalle,
    valtyp = rd_raw$valtyp,
    valdatum = rd_raw$valdatum,
    tidigare_valdatum = rd_raw$tidigareValdatum,
    senaste_uppdateringstid = rd_raw$senasteUppdateringstid,
    
    valdistriktsnamn = vd$namn,
    valdistriktstyp = vd$valdistriktstyp,
    rapporteringstid = vd$rapporteringsTid,
    valdistriktskod = vd$valdistriktskod,
    kommunkod = vd$kommunkod,
    lankod = vd$lankod,
    valomradeskod = vd$valomradeskod,
    kretskod = vd$kretskod,
    kommunvalkretsnamn = vd$kommunvalkretsNamn,
    kommunvalkretskod = vd$kommunvalkretsKod,
    
    totalt_antal_roster = vd$totaltAntalRoster,
    antal_rostberattigade = vd$antalRostberattigade,
    valdeltagande = vd$valdeltagandeVallokal,
    giltiga_roster = vd$rostfordelning$rosterPaverkaMandat$antalRoster,
    ogiltiga_roster = vd$rostfordelning$rosterEjPaverkaMandat$antalRoster,
    roster_ej_anmalt_deltagande =
      vd$rostfordelning$rosterEjPaverkaMandat$rosterEjAnmaltDeltagande$antalRoster,
    blanka_roster =
      vd$rostfordelning$rosterEjPaverkaMandat$blankaRoster$antalRoster,
    ovriga_ogiltiga =
      vd$rostfordelning$rosterEjPaverkaMandat$ovrigaOgiltiga$antalRoster,
    
    valdistriktskod_foregaende_val = vd$valdistriktskodForegaendeVal,
    totalt_antal_roster_foregaende_val = vd$totaltAntalRosterForegaendeVal,
    antal_rostberattigade_foregaende_val = vd$antalRostberattigadeForegaendeVal,
    valdeltagande_foregaende_val = vd$valdeltagandeForegaendeVal,
    status_jamforelse = vd$statusJamforelse
  )

glimpse(valresultat_test)
View(valresultat_test)

vd$valdistriktskodForegaendeVal
str(vd$valdistriktskodForegaendeVal)

map_int(
  rd_raw$valdistrikt,
  ~ length(.x$valdistriktskodForegaendeVal)
) |>
  table()
```

```{r}
str(
  vd$rostfordelning$rosterPaverkaMandat$rosterOvrigaPartier,
  max.level = 2
)

str(
  vd$rostfordelning$rosterEjPaverkaMandat,
  max.level = 3
)

names(vd$rostfordelning$rosterEjPaverkaMandat$rosterEjAnmaltDeltagande)
names(vd$rostfordelning$rosterEjPaverkaMandat$blankaRoster)
names(vd$rostfordelning$rosterEjPaverkaMandat$ovrigaOgiltiga)

```

```{r}
partier <- partier |>
  mutate(
    ovriga_partier = partityp == "ovriga_partier",
    partityp = NULL,
    .after = ordningsnummer
  ) |>
  rename(
    antal_roster_fg = antal_roster_foregaende_val,
    andel_roster_fg = andel_roster_foregaende_val,
    diff_antal_roster = forandring_antal_roster,
    diff_andel_roster = forandring_andel_roster
  )

giltiga <- vd$rostfordelning$rosterPaverkaMandat
ogiltiga <- vd$rostfordelning$rosterEjPaverkaMandat

valresultat_test <- partier |>
  mutate(
    # Val
    valtillfalle = rd_raw$valtillfalle,
    valklass = rd_raw$valklass,
    rakningstillfalle = rd_raw$rakningstillfalle,
    valtyp = rd_raw$valtyp,
    valdatum = rd_raw$valdatum,
    valdatum_fg = rd_raw$tidigareValdatum,
    test = rd_raw$test,

    # Rapportering
    senaste_uppdateringstid = rd_raw$senasteUppdateringstid,
    antal_uppdateringar = rd_raw$antalUppdateringar,
    antal_valdistrikt_raknade = rd_raw$antalValdistriktRaknade,
    antal_valdistrikt_som_ska_raknas = rd_raw$antalValdistriktSomSkaRaknas,
    rapporteringstid = vd$rapporteringsTid,

    # Geografi
    valdistriktsnamn = vd$namn,
    valdistriktstyp = vd$valdistriktstyp,
    valdistriktskod = vd$valdistriktskod,
    kommunkod = vd$kommunkod,
    lankod = vd$lankod,
    valomradeskod = vd$valomradeskod,
    kretskod = vd$kretskod,
    kommunvalkretsnamn = vd$kommunvalkretsNamn,
    kommunvalkretskod = vd$kommunvalkretsKod,

    .before = partibeteckning
  )

valresultat_test <- valresultat_test |>
  mutate(
    totalt_antal_roster = vd$totaltAntalRoster,
    antal_rostberattigade = vd$antalRostberattigade,
    valdel = vd$valdeltagandeVallokal,

    giltiga_roster = giltiga$antalRoster,

    ogiltiga_roster = ogiltiga$antalRoster,
    andel_ogiltiga = ogiltiga$andelRosterAvTotaltAntalRoster,

    roster_ej_anmalt_deltagande =
      ogiltiga$rosterEjAnmaltDeltagande$antalRoster,
    andel_ej_anmalt_deltagande =
      ogiltiga$rosterEjAnmaltDeltagande$andelRosterAvTotaltAntalRoster,

    blanka_roster = ogiltiga$blankaRoster$antalRoster,
    andel_blanka =
      ogiltiga$blankaRoster$andelRosterAvTotaltAntalRoster,

    ovriga_ogiltiga = ogiltiga$ovrigaOgiltiga$antalRoster,
    andel_ovriga_ogiltiga =
      ogiltiga$ovrigaOgiltiga$andelRosterAvTotaltAntalRoster,

    .before = antal_roster_fg
  )

valresultat_test <- valresultat_test |>
  mutate(
    totalt_antal_roster_fg = vd$totaltAntalRosterForegaendeVal,
    antal_rostberattigade_fg = vd$antalRostberattigadeForegaendeVal,
    valdel_fg = vd$valdeltagandeForegaendeVal,

    giltiga_roster_fg = giltiga$antalRosterForegaendeVal,

    ogiltiga_roster_fg = ogiltiga$antalRosterForegaendeVal,
    andel_ogiltiga_fg =
      ogiltiga$andelRosterAvTotaltAntalRosterForegaendeVal,

    roster_ej_anmalt_deltagande_fg =
      ogiltiga$rosterEjAnmaltDeltagande$antalRosterForegaendeVal,
    andel_ej_anmalt_deltagande_fg =
      ogiltiga$rosterEjAnmaltDeltagande$andelRosterAvTotaltAntalRosterForegaendeVal,

    blanka_roster_fg =
      ogiltiga$blankaRoster$antalRosterForegaendeVal,
    andel_blanka_fg =
      ogiltiga$blankaRoster$andelRosterAvTotaltAntalRosterForegaendeVal,

    ovriga_ogiltiga_fg =
      ogiltiga$ovrigaOgiltiga$antalRosterForegaendeVal,
    andel_ovriga_ogiltiga_fg =
      ogiltiga$ovrigaOgiltiga$andelRosterAvTotaltAntalRosterForegaendeVal,

    .before = diff_antal_roster
  )

valresultat_test <- valresultat_test |>
  mutate(
    diff_totalt_antal_roster = vd$forandringTotaltAntalRoster,
    diff_antal_rostberattigade = vd$forandringAntalRostberattigade,
    diff_valdel = vd$forandringValdeltagande,

    diff_giltiga_roster = giltiga$forandringAntalRoster,

    diff_ogiltiga_roster = ogiltiga$forandringAntalRoster,
    diff_andel_ogiltiga =
      ogiltiga$forandringAndelRosterAvTotaltAntalRoster,

    diff_roster_ej_anmalt_deltagande =
      ogiltiga$rosterEjAnmaltDeltagande$forandringAntalRoster,
    diff_andel_ej_anmalt_deltagande =
      ogiltiga$rosterEjAnmaltDeltagande$forandringAndelRosterAvTotaltAntalRoster,

    diff_blanka_roster =
      ogiltiga$blankaRoster$forandringAntalRoster,
    diff_andel_blanka =
      ogiltiga$blankaRoster$forandringAndelRosterAvTotaltAntalRoster,

    diff_ovriga_ogiltiga =
      ogiltiga$ovrigaOgiltiga$forandringAntalRoster,
    diff_andel_ovriga_ogiltiga =
      ogiltiga$ovrigaOgiltiga$forandringAndelRosterAvTotaltAntalRoster,

    status_jamforelse = vd$statusJamforelse,

    .after = diff_andel_roster
  )

glimpse(valresultat_test)
View(valresultat_test)

vd$totaltAntalRoster ==
  giltiga$antalRoster + ogiltiga$antalRoster

sum(valresultat_test$antal_roster) ==
  giltiga$antalRoster

ogiltiga$antalRoster ==
  ogiltiga$rosterEjAnmaltDeltagande$antalRoster +
  ogiltiga$blankaRoster$antalRoster +
  ogiltiga$ovrigaOgiltiga$antalRoster

```


```{r}
scalar_or_na <- function(x, type = c("character", "integer", "double", "logical")) {
  type <- match.arg(type)

  if (is.null(x) || length(x) == 0) {
    return(
      switch(
        type,
        character = NA_character_,
        integer = NA_integer_,
        double = NA_real_,
        logical = NA
      )
    )
  }

  switch(
    type,
    character = as.character(x[[1]]),
    integer = as.integer(x[[1]]),
    double = as.double(x[[1]]),
    logical = as.logical(x[[1]])
  )
}
```

```{r}
parse_valdistrikt_2026 <- function(vd, meta) {

  giltiga <- vd$rostfordelning$rosterPaverkaMandat
  ogiltiga <- vd$rostfordelning$rosterEjPaverkaMandat

  partirader <- giltiga$partiRoster |>
    map(\(x) tibble(
      partibeteckning = scalar_or_na(x$partibeteckning, "character"),
      partiforkortning = scalar_or_na(x$partiforkortning, "character"),
      partikod = scalar_or_na(x$partikod, "character"),
      fargkod = scalar_or_na(x$fargkod, "character"),
      ordningsnummer = scalar_or_na(x$ordningsnummer, "integer"),
      ovriga_partier = FALSE,
      antal_roster = scalar_or_na(x$antalRoster, "integer"),
      andel_roster = scalar_or_na(x$andelRoster, "double"),
      antal_roster_fg = scalar_or_na(x$antalRosterForegaendeVal, "integer"),
      andel_roster_fg = scalar_or_na(x$andelRosterForegaendeVal, "double"),
      diff_antal_roster = scalar_or_na(x$forandringAntalRoster, "integer"),
      diff_andel_roster = scalar_or_na(x$forandringAndelRoster, "double")
    )) |>
    list_rbind() |>
    bind_rows(
      tibble(
        partibeteckning = "Övriga partier",
        partiforkortning = NA_character_,
        partikod = NA_character_,
        fargkod = NA_character_,
        ordningsnummer = NA_integer_,
        ovriga_partier = TRUE,
        antal_roster =
          scalar_or_na(giltiga$rosterOvrigaPartier$antalRoster, "integer"),
        andel_roster =
          scalar_or_na(giltiga$rosterOvrigaPartier$andelRoster, "double"),
        antal_roster_fg =
          scalar_or_na(giltiga$rosterOvrigaPartier$antalRosterForegaendeVal, "integer"),
        andel_roster_fg =
          scalar_or_na(giltiga$rosterOvrigaPartier$andelRosterForegaendeVal, "double"),
        diff_antal_roster =
          scalar_or_na(giltiga$rosterOvrigaPartier$forandringAntalRoster, "integer"),
        diff_andel_roster =
          scalar_or_na(giltiga$rosterOvrigaPartier$forandringAndelRoster, "double")
      )
    )

  partirader |>
    mutate(
      # Val
      valtillfalle = scalar_or_na(meta$valtillfalle, "character"),
      valklass = scalar_or_na(meta$valklass, "character"),
      rakningstillfalle = scalar_or_na(meta$rakningstillfalle, "character"),
      valtyp = scalar_or_na(meta$valtyp, "character"),
      valdatum = scalar_or_na(meta$valdatum, "character"),
      valdatum_fg = scalar_or_na(meta$tidigareValdatum, "character"),
      test = scalar_or_na(meta$test, "logical"),

      # Rapportering
      senaste_uppdateringstid =
        scalar_or_na(meta$senasteUppdateringstid, "character"),
      antal_uppdateringar =
        scalar_or_na(meta$antalUppdateringar, "integer"),
      antal_valdistrikt_raknade =
        scalar_or_na(meta$antalValdistriktRaknade, "integer"),
      antal_valdistrikt_som_ska_raknas =
        scalar_or_na(meta$antalValdistriktSomSkaRaknas, "integer"),
      rapporteringstid =
        scalar_or_na(vd$rapporteringsTid, "character"),

      # Geografi
      valdistriktsnamn = scalar_or_na(vd$namn, "character"),
      valdistriktstyp = scalar_or_na(vd$valdistriktstyp, "character"),
      valdistriktskod = scalar_or_na(vd$valdistriktskod, "character"),
      kommunkod = scalar_or_na(vd$kommunkod, "character"),
      lankod = scalar_or_na(vd$lankod, "character"),
      valomradeskod = scalar_or_na(vd$valomradeskod, "character"),
      kretskod = scalar_or_na(vd$kretskod, "character"),
      kommunvalkretsnamn =
        scalar_or_na(vd$kommunvalkretsNamn, "character"),
      kommunvalkretskod =
        scalar_or_na(vd$kommunvalkretsKod, "character"),

      # Parti
      partibeteckning = partibeteckning,
      partiforkortning = partiforkortning,
      partikod = partikod,
      fargkod = fargkod,
      ordningsnummer = ordningsnummer,
      ovriga_partier = ovriga_partier,

      # Aktuellt resultat
      antal_roster = antal_roster,
      andel_roster = andel_roster,

      totalt_antal_roster =
        scalar_or_na(vd$totaltAntalRoster, "integer"),
      antal_rostberattigade =
        scalar_or_na(vd$antalRostberattigade, "integer"),
      valdel =
        scalar_or_na(vd$valdeltagandeVallokal, "double"),

      giltiga_roster =
        scalar_or_na(giltiga$antalRoster, "integer"),

      ogiltiga_roster =
        scalar_or_na(ogiltiga$antalRoster, "integer"),
      andel_ogiltiga =
        scalar_or_na(ogiltiga$andelRosterAvTotaltAntalRoster, "double"),

      roster_ej_anmalt_deltagande =
        scalar_or_na(
          ogiltiga$rosterEjAnmaltDeltagande$antalRoster,
          "integer"
        ),
      andel_ej_anmalt_deltagande =
        scalar_or_na(
          ogiltiga$rosterEjAnmaltDeltagande$andelRosterAvTotaltAntalRoster,
          "double"
        ),

      blanka_roster =
        scalar_or_na(ogiltiga$blankaRoster$antalRoster, "integer"),
      andel_blanka =
        scalar_or_na(
          ogiltiga$blankaRoster$andelRosterAvTotaltAntalRoster,
          "double"
        ),

      ovriga_ogiltiga =
        scalar_or_na(ogiltiga$ovrigaOgiltiga$antalRoster, "integer"),
      andel_ovriga_ogiltiga =
        scalar_or_na(
          ogiltiga$ovrigaOgiltiga$andelRosterAvTotaltAntalRoster,
          "double"
        ),

      # Föregående val
      antal_roster_fg = antal_roster_fg,
      andel_roster_fg = andel_roster_fg,

      totalt_antal_roster_fg =
        scalar_or_na(vd$totaltAntalRosterForegaendeVal, "integer"),
      antal_rostberattigade_fg =
        scalar_or_na(vd$antalRostberattigadeForegaendeVal, "integer"),
      valdel_fg =
        scalar_or_na(vd$valdeltagandeForegaendeVal, "double"),

      giltiga_roster_fg =
        scalar_or_na(giltiga$antalRosterForegaendeVal, "integer"),

      ogiltiga_roster_fg =
        scalar_or_na(ogiltiga$antalRosterForegaendeVal, "integer"),
      andel_ogiltiga_fg =
        scalar_or_na(
          ogiltiga$andelRosterAvTotaltAntalRosterForegaendeVal,
          "double"
        ),

      roster_ej_anmalt_deltagande_fg =
        scalar_or_na(
          ogiltiga$rosterEjAnmaltDeltagande$antalRosterForegaendeVal,
          "integer"
        ),
      andel_ej_anmalt_deltagande_fg =
        scalar_or_na(
          ogiltiga$rosterEjAnmaltDeltagande$
            andelRosterAvTotaltAntalRosterForegaendeVal,
          "double"
        ),

      blanka_roster_fg =
        scalar_or_na(
          ogiltiga$blankaRoster$antalRosterForegaendeVal,
          "integer"
        ),
      andel_blanka_fg =
        scalar_or_na(
          ogiltiga$blankaRoster$
            andelRosterAvTotaltAntalRosterForegaendeVal,
          "double"
        ),

      ovriga_ogiltiga_fg =
        scalar_or_na(
          ogiltiga$ovrigaOgiltiga$antalRosterForegaendeVal,
          "integer"
        ),
      andel_ovriga_ogiltiga_fg =
        scalar_or_na(
          ogiltiga$ovrigaOgiltiga$
            andelRosterAvTotaltAntalRosterForegaendeVal,
          "double"
        ),

      # Differenser
      diff_antal_roster = diff_antal_roster,
      diff_andel_roster = diff_andel_roster,

      diff_totalt_antal_roster =
        scalar_or_na(vd$forandringTotaltAntalRoster, "integer"),
      diff_antal_rostberattigade =
        scalar_or_na(vd$forandringAntalRostberattigade, "integer"),
      diff_valdel =
        scalar_or_na(vd$forandringValdeltagande, "double"),

      diff_giltiga_roster =
        scalar_or_na(giltiga$forandringAntalRoster, "integer"),

      diff_ogiltiga_roster =
        scalar_or_na(ogiltiga$forandringAntalRoster, "integer"),
      diff_andel_ogiltiga =
        scalar_or_na(
          ogiltiga$forandringAndelRosterAvTotaltAntalRoster,
          "double"
        ),

      diff_roster_ej_anmalt_deltagande =
        scalar_or_na(
          ogiltiga$rosterEjAnmaltDeltagande$forandringAntalRoster,
          "integer"
        ),
      diff_andel_ej_anmalt_deltagande =
        scalar_or_na(
          ogiltiga$rosterEjAnmaltDeltagande$
            forandringAndelRosterAvTotaltAntalRoster,
          "double"
        ),

      diff_blanka_roster =
        scalar_or_na(
          ogiltiga$blankaRoster$forandringAntalRoster,
          "integer"
        ),
      diff_andel_blanka =
        scalar_or_na(
          ogiltiga$blankaRoster$
            forandringAndelRosterAvTotaltAntalRoster,
          "double"
        ),

      diff_ovriga_ogiltiga =
        scalar_or_na(
          ogiltiga$ovrigaOgiltiga$forandringAntalRoster,
          "integer"
        ),
      diff_andel_ovriga_ogiltiga =
        scalar_or_na(
          ogiltiga$ovrigaOgiltiga$
            forandringAndelRosterAvTotaltAntalRoster,
          "double"
        ),

      status_jamforelse =
        scalar_or_na(vd$statusJamforelse, "character"),

      .keep = "none"
    )
}

valresultat_test2 <- parse_valdistrikt_2026(vd, rd_raw)

glimpse(valresultat_test2)
View(valresultat_test2)

vd_uppsamling <- rd_raw$valdistrikt[
  map_chr(rd_raw$valdistrikt, "valdistriktstyp") == "uppsamlingsdistrikt"
][[1]]

valresultat_uppsamling <- parse_valdistrikt_2026(
  vd_uppsamling,
  rd_raw
)

glimpse(valresultat_uppsamling)
View(valresultat_uppsamling)

valresultat_uppsamling |>
  select(
    valdistriktsnamn, valdistriktstyp,
    totalt_antal_roster, antal_rostberattigade, valdel,
    giltiga_roster, ogiltiga_roster,
    totalt_antal_roster_fg, valdel_fg,
    status_jamforelse
  ) |>
  distinct() |> 
  View()

with(
  valresultat_uppsamling[1, ],
  totalt_antal_roster == giltiga_roster + ogiltiga_roster
)

sum(valresultat_uppsamling$antal_roster, na.rm = TRUE) ==
  valresultat_uppsamling$giltiga_roster[1]

with(
  valresultat_uppsamling[1, ],
  ogiltiga_roster ==
    roster_ej_anmalt_deltagande +
    blanka_roster +
    ovriga_ogiltiga
)

map_lgl(valresultat_uppsamling, is.list) |>
  which()
```

```{r}
valresultat <- rd_raw$valdistrikt |>
  map(\(x) parse_valdistrikt_2026(x, rd_raw)) |>
  list_rbind()

glimpse(valresultat)

nrow(valresultat)
n_distinct(valresultat$valdistriktskod)

map_lgl(valresultat, is.list) |>
  which()

valresultat |>
  count(
    valtyp,
    valdistriktskod,
    partikod,
    ovriga_partier
  ) |>
  filter(n > 1)

kontroll <- valresultat |>
  summarise(
    partisumma = sum(antal_roster, na.rm = TRUE),
    giltiga_roster = first(giltiga_roster),
    totalt_antal_roster = first(totalt_antal_roster),
    ogiltiga_roster = first(ogiltiga_roster),
    summa_ogiltiga =
      first(roster_ej_anmalt_deltagande) +
      first(blanka_roster) +
      first(ovriga_ogiltiga),
    .by = valdistriktskod
  )

kontroll |>
  filter(partisumma != giltiga_roster)

kontroll |>
  filter(totalt_antal_roster != giltiga_roster + ogiltiga_roster)

kontroll |>
  filter(ogiltiga_roster != summa_ogiltiga)

valresultat |>
  distinct(valdistriktskod, valdistriktstyp, status_jamforelse) |>
  count(valdistriktstyp, status_jamforelse)

```



```{r}
chr1 <- \(x) scalar_or_na(x, "character")
int1 <- \(x) scalar_or_na(x, "integer")
dbl1 <- \(x) scalar_or_na(x, "double")
lgl1 <- \(x) scalar_or_na(x, "logical")

parse_rostfordelning_2026 <- function(raw) {

  vd <- raw$valdistrikt
  vd_id <- seq_along(vd)

  # Distriktsnivå ----------------------------------------------------------

  distrikt <- tibble(
    vd_id = vd_id,

    # Rapportering
    rapporteringstid =
      map_chr(vd, \(x) chr1(x$rapporteringsTid)),

    # Geografi
    valdistriktsnamn =
      map_chr(vd, \(x) chr1(x$namn)),
    valdistriktstyp =
      map_chr(vd, \(x) chr1(x$valdistriktstyp)),
    valdistriktskod =
      map_chr(vd, \(x) chr1(x$valdistriktskod)),
    kommunkod =
      map_chr(vd, \(x) chr1(x$kommunkod)),
    lankod =
      map_chr(vd, \(x) chr1(x$lankod)),
    valomradeskod =
      map_chr(vd, \(x) chr1(x$valomradeskod)),
    kretskod =
      map_chr(vd, \(x) chr1(x$kretskod)),
    kommunvalkretsnamn =
      map_chr(vd, \(x) chr1(x$kommunvalkretsNamn)),
    kommunvalkretskod =
      map_chr(vd, \(x) chr1(x$kommunvalkretsKod)),

    # Aktuellt resultat
    totalt_antal_roster =
      map_int(vd, \(x) int1(x$totaltAntalRoster)),
    antal_rostberattigade =
      map_int(vd, \(x) int1(x$antalRostberattigade)),
    valdel =
      map_dbl(vd, \(x) dbl1(x$valdeltagandeVallokal)),

    giltiga_roster =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterPaverkaMandat$antalRoster
        )
      ),

    ogiltiga_roster =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$antalRoster
        )
      ),
    andel_ogiltiga =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            andelRosterAvTotaltAntalRoster
        )
      ),

    roster_ej_anmalt_deltagande =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            rosterEjAnmaltDeltagande$antalRoster
        )
      ),
    andel_ej_anmalt_deltagande =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            rosterEjAnmaltDeltagande$andelRosterAvTotaltAntalRoster
        )
      ),

    blanka_roster =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            blankaRoster$antalRoster
        )
      ),
    andel_blanka =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            blankaRoster$andelRosterAvTotaltAntalRoster
        )
      ),

    ovriga_ogiltiga =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            ovrigaOgiltiga$antalRoster
        )
      ),
    andel_ovriga_ogiltiga =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            ovrigaOgiltiga$andelRosterAvTotaltAntalRoster
        )
      ),

    # Föregående val
    totalt_antal_roster_fg =
      map_int(vd, \(x) int1(x$totaltAntalRosterForegaendeVal)),
    antal_rostberattigade_fg =
      map_int(vd, \(x) int1(x$antalRostberattigadeForegaendeVal)),
    valdel_fg =
      map_dbl(vd, \(x) dbl1(x$valdeltagandeForegaendeVal)),

    giltiga_roster_fg =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterPaverkaMandat$
            antalRosterForegaendeVal
        )
      ),

    ogiltiga_roster_fg =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            antalRosterForegaendeVal
        )
      ),
    andel_ogiltiga_fg =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            andelRosterAvTotaltAntalRosterForegaendeVal
        )
      ),

    roster_ej_anmalt_deltagande_fg =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            rosterEjAnmaltDeltagande$antalRosterForegaendeVal
        )
      ),
    andel_ej_anmalt_deltagande_fg =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            rosterEjAnmaltDeltagande$
            andelRosterAvTotaltAntalRosterForegaendeVal
        )
      ),

    blanka_roster_fg =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            blankaRoster$antalRosterForegaendeVal
        )
      ),
    andel_blanka_fg =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            blankaRoster$
            andelRosterAvTotaltAntalRosterForegaendeVal
        )
      ),

    ovriga_ogiltiga_fg =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            ovrigaOgiltiga$antalRosterForegaendeVal
        )
      ),
    andel_ovriga_ogiltiga_fg =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            ovrigaOgiltiga$
            andelRosterAvTotaltAntalRosterForegaendeVal
        )
      ),

    # Differenser
    diff_totalt_antal_roster =
      map_int(vd, \(x) int1(x$forandringTotaltAntalRoster)),
    diff_antal_rostberattigade =
      map_int(vd, \(x) int1(x$forandringAntalRostberattigade)),
    diff_valdel =
      map_dbl(vd, \(x) dbl1(x$forandringValdeltagande)),

    diff_giltiga_roster =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterPaverkaMandat$
            forandringAntalRoster
        )
      ),

    diff_ogiltiga_roster =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            forandringAntalRoster
        )
      ),
    diff_andel_ogiltiga =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            forandringAndelRosterAvTotaltAntalRoster
        )
      ),

    diff_roster_ej_anmalt_deltagande =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            rosterEjAnmaltDeltagande$forandringAntalRoster
        )
      ),
    diff_andel_ej_anmalt_deltagande =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            rosterEjAnmaltDeltagande$
            forandringAndelRosterAvTotaltAntalRoster
        )
      ),

    diff_blanka_roster =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            blankaRoster$forandringAntalRoster
        )
      ),
    diff_andel_blanka =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            blankaRoster$
            forandringAndelRosterAvTotaltAntalRoster
        )
      ),

    diff_ovriga_ogiltiga =
      map_int(
        vd,
        \(x) int1(
          x$rostfordelning$rosterEjPaverkaMandat$
            ovrigaOgiltiga$forandringAntalRoster
        )
      ),
    diff_andel_ovriga_ogiltiga =
      map_dbl(
        vd,
        \(x) dbl1(
          x$rostfordelning$rosterEjPaverkaMandat$
            ovrigaOgiltiga$
            forandringAndelRosterAvTotaltAntalRoster
        )
      ),

    status_jamforelse =
      map_chr(vd, \(x) chr1(x$statusJamforelse))
  )

  # Vanliga partirader -----------------------------------------------------

  parti_list <- map(
    vd,
    \(x) x$rostfordelning$rosterPaverkaMandat$partiRoster
  )

  parti_flat <- unlist(
    parti_list,
    recursive = FALSE,
    use.names = FALSE
  )

  partier <- tibble(
    vd_id = rep(vd_id, lengths(parti_list)),
    partibeteckning =
      map_chr(parti_flat, \(x) chr1(x$partibeteckning)),
    partiforkortning =
      map_chr(parti_flat, \(x) chr1(x$partiforkortning)),
    partikod =
      map_chr(parti_flat, \(x) chr1(x$partikod)),
    fargkod =
      map_chr(parti_flat, \(x) chr1(x$fargkod)),
    ordningsnummer =
      map_int(parti_flat, \(x) int1(x$ordningsnummer)),
    ovriga_partier = FALSE,
    antal_roster =
      map_int(parti_flat, \(x) int1(x$antalRoster)),
    andel_roster =
      map_dbl(parti_flat, \(x) dbl1(x$andelRoster)),
    antal_roster_fg =
      map_int(parti_flat, \(x) int1(x$antalRosterForegaendeVal)),
    andel_roster_fg =
      map_dbl(parti_flat, \(x) dbl1(x$andelRosterForegaendeVal)),
    diff_antal_roster =
      map_int(parti_flat, \(x) int1(x$forandringAntalRoster)),
    diff_andel_roster =
      map_dbl(parti_flat, \(x) dbl1(x$forandringAndelRoster))
  )

  # Övriga partier --------------------------------------------------------

  ovriga_list <- map(
    vd,
    \(x) x$rostfordelning$rosterPaverkaMandat$rosterOvrigaPartier
  )

  ovriga <- tibble(
    vd_id = vd_id,
    partibeteckning = "Övriga partier",
    partiforkortning = NA_character_,
    partikod = NA_character_,
    fargkod = NA_character_,
    ordningsnummer = NA_integer_,
    ovriga_partier = TRUE,
    antal_roster =
      map_int(ovriga_list, \(x) int1(x$antalRoster)),
    andel_roster =
      map_dbl(ovriga_list, \(x) dbl1(x$andelRoster)),
    antal_roster_fg =
      map_int(ovriga_list, \(x) int1(x$antalRosterForegaendeVal)),
    andel_roster_fg =
      map_dbl(ovriga_list, \(x) dbl1(x$andelRosterForegaendeVal)),
    diff_antal_roster =
      map_int(ovriga_list, \(x) int1(x$forandringAntalRoster)),
    diff_andel_roster =
      map_dbl(ovriga_list, \(x) dbl1(x$forandringAndelRoster))
  )

  # Slutligt dataset ------------------------------------------------------

  bind_rows(partier, ovriga) |>
    arrange(vd_id, ovriga_partier, ordningsnummer) |>
    left_join(distrikt, by = join_by(vd_id)) |>
    transmute(
      # Val
      valtillfalle = chr1(raw$valtillfalle),
      valklass = chr1(raw$valklass),
      rakningstillfalle = chr1(raw$rakningstillfalle),
      valtyp = chr1(raw$valtyp),
      valdatum = chr1(raw$valdatum),
      valdatum_fg = chr1(raw$tidigareValdatum),
      test = lgl1(raw$test),

      # Rapportering
      senaste_uppdateringstid =
        chr1(raw$senasteUppdateringstid),
      antal_uppdateringar =
        int1(raw$antalUppdateringar),
      antal_valdistrikt_raknade =
        int1(raw$antalValdistriktRaknade),
      antal_valdistrikt_som_ska_raknas =
        int1(raw$antalValdistriktSomSkaRaknas),
      rapporteringstid,

      # Geografi
      valdistriktsnamn,
      valdistriktstyp,
      valdistriktskod,
      kommunkod,
      lankod,
      valomradeskod,
      kretskod,
      kommunvalkretsnamn,
      kommunvalkretskod,

      # Parti
      partibeteckning,
      partiforkortning,
      partikod,
      fargkod,
      ordningsnummer,
      ovriga_partier,

      # Aktuellt resultat
      antal_roster,
      andel_roster,
      totalt_antal_roster,
      antal_rostberattigade,
      valdel,
      giltiga_roster,
      ogiltiga_roster,
      andel_ogiltiga,
      roster_ej_anmalt_deltagande,
      andel_ej_anmalt_deltagande,
      blanka_roster,
      andel_blanka,
      ovriga_ogiltiga,
      andel_ovriga_ogiltiga,

      # Föregående val
      antal_roster_fg,
      andel_roster_fg,
      totalt_antal_roster_fg,
      antal_rostberattigade_fg,
      valdel_fg,
      giltiga_roster_fg,
      ogiltiga_roster_fg,
      andel_ogiltiga_fg,
      roster_ej_anmalt_deltagande_fg,
      andel_ej_anmalt_deltagande_fg,
      blanka_roster_fg,
      andel_blanka_fg,
      ovriga_ogiltiga_fg,
      andel_ovriga_ogiltiga_fg,

      # Differenser
      diff_antal_roster,
      diff_andel_roster,
      diff_totalt_antal_roster,
      diff_antal_rostberattigade,
      diff_valdel,
      diff_giltiga_roster,
      diff_ogiltiga_roster,
      diff_andel_ogiltiga,
      diff_roster_ej_anmalt_deltagande,
      diff_andel_ej_anmalt_deltagande,
      diff_blanka_roster,
      diff_andel_blanka,
      diff_ovriga_ogiltiga,
      diff_andel_ovriga_ogiltiga,

      status_jamforelse
    )
}

system.time({
  valresultat_bulk <- parse_rostfordelning_2026(rd_raw)
})

all.equal(
  valresultat,
  valresultat_bulk
)

setdiff(names(valresultat), names(valresultat_bulk))
setdiff(names(valresultat_bulk), names(valresultat))

valresultat_old_ordnad <- valresultat |>
  select(all_of(names(valresultat_bulk)))

all.equal(
  valresultat_old_ordnad,
  valresultat_bulk
)

```


```{r}
parse_valdistriktskoppling_2026 <- function(raw) {

  vd <- raw$valdistrikt

  kopplingar <- map(
    vd,
    \(x) x$valdistriktskodForegaendeVal
  )

  n_kopplingar <- lengths(kopplingar)

  tibble(
    valtyp = chr1(raw$valtyp),
    valdatum = chr1(raw$valdatum),
    valdatum_fg = chr1(raw$tidigareValdatum),

    valdistriktskod =
      rep(
        map_chr(vd, \(x) chr1(x$valdistriktskod)),
        n_kopplingar
      ),

    valdistriktsnamn =
      rep(
        map_chr(vd, \(x) chr1(x$namn)),
        n_kopplingar
      ),

    valdistriktskod_fg =
      unlist(
        kopplingar,
        use.names = FALSE
      ),

    status_jamforelse =
      rep(
        map_chr(vd, \(x) chr1(x$statusJamforelse)),
        n_kopplingar
      )
  )
}

valdistriktskoppling <- parse_valdistriktskoppling_2026(rd_raw)

glimpse(valdistriktskoppling)


nrow(valdistriktskoppling)

valdistriktskoppling |>
  count(status_jamforelse)

```


```{r}
source("R/utils.R")
source("R/parse_rostfordelning_2026.R")


kf_0180_line <- grep(
  "/p/kf/.*0180_KF\\.zip$",
  index,
  value = TRUE
)

kf_0180_line

kf_0180_path <- kf_0180_line |>
  str_remove("^[0-9a-f]+\\s+\\./")

kf_0180_url <- paste0(base_url, "/", kf_0180_path)

kf_0180_zip <- tempfile(fileext = ".zip")
download.file(kf_0180_url, kf_0180_zip, mode = "wb")

unzip(kf_0180_zip, list = TRUE)

kf_0180_files <- unzip(kf_0180_zip, list = TRUE)

kf_0180_rost_file <- kf_0180_files$Name |>
  str_subset("rostfordelning.*0180_KF\\.json$")

kf_0180_rost_file


kf_0180_dir <- tempfile()
dir.create(kf_0180_dir)

unzip(
  kf_0180_zip,
  files = kf_0180_rost_file,
  exdir = kf_0180_dir
)

kf_0180_raw <- fromJSON(
  file.path(kf_0180_dir, kf_0180_rost_file),
  simplifyVector = FALSE
)

kf_0180_raw$valtyp
length(kf_0180_raw$valdistrikt)
names(kf_0180_raw)

system.time({
  valresultat_kf_0180 <- parse_rostfordelning_2026(kf_0180_raw)
})

glimpse(valresultat_kf_0180)

nrow(valresultat_kf_0180)
n_distinct(valresultat_kf_0180$valdistriktskod)

unique(valresultat_kf_0180$valtyp)
unique(valresultat_kf_0180$kommunkod)

map_lgl(valresultat_kf_0180, is.list) |>
  which()


kontroll_kf <- valresultat_kf_0180 |>
  summarise(
    partisumma = sum(antal_roster, na.rm = TRUE),
    giltiga_roster = first(giltiga_roster),
    totalt_antal_roster = first(totalt_antal_roster),
    ogiltiga_roster = first(ogiltiga_roster),
    summa_ogiltiga =
      first(roster_ej_anmalt_deltagande) +
      first(blanka_roster) +
      first(ovriga_ogiltiga),
    .by = valdistriktskod
  )

kontroll_kf |>
  filter(partisumma != giltiga_roster)

kontroll_kf |>
  filter(totalt_antal_roster != giltiga_roster + ogiltiga_roster)

kontroll_kf |>
  filter(ogiltiga_roster != summa_ogiltiga)

```



```{r}
read_rostfordelning_zip_2026 <- function(zip_file) {

  remove_zip <- FALSE

  if (grepl("^https?://", zip_file)) {
    tmp_zip <- tempfile(fileext = ".zip")
    download.file(zip_file, tmp_zip, mode = "wb", quiet = TRUE)
    zip_file <- tmp_zip
    remove_zip <- TRUE
  }

  if (remove_zip) {
    on.exit(unlink(zip_file), add = TRUE)
  }

  files <- unzip(zip_file, list = TRUE)

  rost_file <- files$Name |>
    stringr::str_subset("rostfordelning.*\\.json$") |>
    stringr::str_subset("_sign\\.sha256$", negate = TRUE)

  if (length(rost_file) != 1) {
    stop(
      "Förväntade mig exakt en röstfördelningsfil i ZIP-filen, men hittade ",
      length(rost_file),
      "."
    )
  }

  tmp_dir <- tempfile()
  dir.create(tmp_dir)
  on.exit(unlink(tmp_dir, recursive = TRUE), add = TRUE)

  unzip(
    zip_file,
    files = rost_file,
    exdir = tmp_dir
  )

  raw <- jsonlite::fromJSON(
    file.path(tmp_dir, rost_file),
    simplifyVector = FALSE
  )

  parse_rostfordelning_2026(raw)
}

parse_index_2026 <- function(index) {

  match <- stringr::str_match(
    index,
    "^([0-9a-f]+)\\s+\\./(.+)$"
  )

  tibble::tibble(
    md5 = match[, 2],
    path = match[, 3]
  ) |>
    dplyr::filter(!is.na(path))
}

index_tbl <- parse_index_2026(index)

kf_files <- index_tbl |>
  filter(str_detect(path, "^p/kf/.*_KF\\.zip$"))

nrow(kf_files)

kf_files |>
  filter(!str_detect(path, "_[0-9]{4}_KF\\.zip$")) |>
  pull(path)

kf_files <- index_tbl |>
  filter(
    str_detect(
      path,
      "^p/kf/.*_[0-9]{4}_KF\\.zip$"
    )
  )

nrow(kf_files)

```



```{r}
kf_test <- kf_files |>
  slice(c(1, 145, 290)) |>
  mutate(
    url = paste0(base_url, "/", path)
  )

kf_test |>
  select(path)

system.time({
  valresultat_kf_test <- kf_test$url |>
    map(read_rostfordelning_zip_2026) |>
    list_rbind()
})

valresultat_kf_test |>
  distinct(kommunkod, valtyp)

n_distinct(valresultat_kf_test$kommunkod)

map_lgl(valresultat_kf_test, is.list) |>
  which()

valresultat_kf_test |>
  count(
    kommunkod,
    valdistriktskod,
    partikod,
    ovriga_partier
  ) |>
  filter(n > 1)

kontroll_kf_test <- valresultat_kf_test |>
  summarise(
    partisumma = sum(antal_roster, na.rm = TRUE),
    giltiga_roster = first(giltiga_roster),
    totalt_antal_roster = first(totalt_antal_roster),
    ogiltiga_roster = first(ogiltiga_roster),
    summa_ogiltiga =
      first(roster_ej_anmalt_deltagande) +
      first(blanka_roster) +
      first(ovriga_ogiltiga),
    .by = c(kommunkod, valdistriktskod)
  )

kontroll_kf_test |>
  filter(partisumma != giltiga_roster)

kontroll_kf_test |>
  filter(totalt_antal_roster != giltiga_roster + ogiltiga_roster)

kontroll_kf_test |>
  filter(ogiltiga_roster != summa_ogiltiga)
```


```{r}
read_kf_file <- function(url) {
  tryCatch(
    read_rostfordelning_zip_2026(url),
    error = \(e) {
      stop(
        "Fel vid läsning av:\n",
        url,
        "\n\n",
        conditionMessage(e),
        call. = FALSE
      )
    }
  )
}

kf_files <- kf_files |>
  mutate(
    url = paste0(base_url, "/", path)
  )

system.time({
  valresultat_kf <- kf_files$url |>
    map(read_kf_file, .progress = TRUE) |>
    list_rbind()
})

n_distinct(valresultat_kf$kommunkod)
n_distinct(valresultat_kf$valdistriktskod)

unique(valresultat_kf$valtyp)

map_lgl(valresultat_kf, is.list) |>
  which()

valresultat_kf |>
  count(
    kommunkod,
    valdistriktskod,
    partikod,
    ovriga_partier
  ) |>
  filter(n > 1)

kontroll_kf <- valresultat_kf |>
  summarise(
    partisumma = sum(antal_roster, na.rm = TRUE),
    giltiga_roster = first(giltiga_roster),
    totalt_antal_roster = first(totalt_antal_roster),
    ogiltiga_roster = first(ogiltiga_roster),
    summa_ogiltiga =
      first(roster_ej_anmalt_deltagande) +
      first(blanka_roster) +
      first(ovriga_ogiltiga),
    .by = c(kommunkod, valdistriktskod)
  )

kontroll_kf |>
  filter(partisumma != giltiga_roster)

kontroll_kf |>
  filter(totalt_antal_roster != giltiga_roster + ogiltiga_roster)

kontroll_kf |>
  filter(ogiltiga_roster != summa_ogiltiga)

```


```{r}
os_kf_file <- index_tbl |>
  filter(str_detect(path, "^p/kf/.*_OS_KF\\.zip$"))

os_kf_file

os_kf_url <- paste0(base_url, "/", os_kf_file$path)

os_kf_zip <- tempfile(fileext = ".zip")
download.file(os_kf_url, os_kf_zip, mode = "wb")

unzip(os_kf_zip, list = TRUE)

os_kf_files <- unzip(os_kf_zip, list = TRUE)

os_kf_json <- os_kf_files$Name |>
  str_subset("\\.json$")

os_kf_json

os_kf_dir <- tempfile()
dir.create(os_kf_dir)

unzip(
  os_kf_zip,
  files = os_kf_json,
  exdir = os_kf_dir
)

os_kf_raw <- fromJSON(
  file.path(os_kf_dir, os_kf_json),
  simplifyVector = FALSE
)

names(os_kf_raw)

names(os_kf_raw$helaLandet)

length(os_kf_raw$helaLandet$lan)

names(os_kf_raw$helaLandet$lan[[1]])

length(os_kf_raw$helaLandet$lan[[1]]$kommuner)

names(os_kf_raw$helaLandet$lan[[1]]$kommuner[[1]])


kommun <- os_kf_raw$helaLandet$lan[[1]]$kommuner[[1]]

kommun$namn
kommun$kommunkod

str(
  kommun$rostfordelning,
  max.level = 3
)
```

```{r}
names(kommun$rostfordelning)

names(
  kommun$rostfordelning$rosterPaverkaMandat
)

names(
  kommun$rostfordelning$rosterPaverkaMandat$partiRoster[[1]]
)

names(
  kommun$rostfordelning$rosterPaverkaMandat$rosterOvrigaPartier
)

names(
  kommun$rostfordelning$rosterEjPaverkaMandat
)



kommun$rostfordelning$rosterPaverkaMandat$partiRoster |>
  map_chr("partibeteckning")
```


```{r}
source("R/parse_summering_kf_2026.R")
system.time({
  valresultat_kommun <- parse_summering_kf_2026(os_kf_raw)
})

glimpse(valresultat_kommun)


n_distinct(valresultat_kommun$kommunkod)

unique(valresultat_kommun$geografiniva)
unique(valresultat_kommun$valtyp)

map_lgl(valresultat_kommun, is.list) |>
  which()

valresultat_kommun |>
  count(kommunkod, partikod, ovriga_partier) |>
  filter(n > 1)

kf_fran_valdistrikt <- valresultat_kf |>
  summarise(
    antal_roster_valdistrikt = sum(antal_roster),
    .by = c(kommunkod, partikod, ovriga_partier)
  )

kontroll_kommun <- valresultat_kommun |>
  select(
    kommunkod,
    partikod,
    ovriga_partier,
    antal_roster
  ) |>
  left_join(
    kf_fran_valdistrikt,
    by = join_by(
      kommunkod,
      partikod,
      ovriga_partier
    )
  ) |>
  filter(
    antal_roster != antal_roster_valdistrikt |
      is.na(antal_roster_valdistrikt)
  )

kontroll_kommun

kf_fran_valdistrikt |>
  anti_join(
    valresultat_kommun,
    by = join_by(
      kommunkod,
      partikod,
      ovriga_partier
    )
  )
```


```{r}
names(os_kf_raw$helaLandet$rostfordelning)
names(os_kf_raw$helaLandet$lan[[1]]$rostfordelning)

str(os_kf_raw$helaLandet, max.level = 1)
str(os_kf_raw$helaLandet$lan[[1]], max.level = 1)


```



```{r}
source("R/utils.R")
source("R/parse_summering_kf_2026.R")

valresultat_kf_summering <- parse_summering_kf_2026(os_kf_raw)

valresultat_kf_summering |>
  distinct(geografiniva, lankod, kommunkod) |>
  count(geografiniva)

map_lgl(valresultat_kf_summering, is.list) |>
  which()

kommun_ny <- valresultat_kf_summering |>
  filter(geografiniva == "kommun") |>
  select(all_of(names(valresultat_kommun)))

all.equal(
  valresultat_kommun,
  kommun_ny
)

kommun_tot <- valresultat_kf_summering |>
  filter(geografiniva == "kommun") |>
  distinct(
    lankod,
    kommunkod,
    totalt_antal_roster,
    giltiga_roster,
    ogiltiga_roster
  )

kontroll_lan <- kommun_tot |>
  summarise(
    totalt_antal_roster_kommun = sum(totalt_antal_roster),
    giltiga_roster_kommun = sum(giltiga_roster),
    ogiltiga_roster_kommun = sum(ogiltiga_roster),
    .by = lankod
  ) |>
  left_join(
    valresultat_kf_summering |>
      filter(geografiniva == "lan") |>
      distinct(
        lankod,
        totalt_antal_roster,
        giltiga_roster,
        ogiltiga_roster
      ),
    by = join_by(lankod)
  ) |>
  filter(
    totalt_antal_roster_kommun != totalt_antal_roster |
      giltiga_roster_kommun != giltiga_roster |
      ogiltiga_roster_kommun != ogiltiga_roster
  )

kontroll_lan

kontroll_riket <- valresultat_kf_summering |>
  filter(geografiniva == "lan") |>
  distinct(
    lankod,
    totalt_antal_roster,
    giltiga_roster,
    ogiltiga_roster
  ) |>
  summarise(
    totalt_antal_roster_lan = sum(totalt_antal_roster),
    giltiga_roster_lan = sum(giltiga_roster),
    ogiltiga_roster_lan = sum(ogiltiga_roster)
  ) |>
  left_join(
    valresultat_kf_summering |>
      filter(geografiniva == "riket") |>
      distinct(
        totalt_antal_roster,
        giltiga_roster,
        ogiltiga_roster
      ),
    by = character()
  ) |>
  filter(
    totalt_antal_roster_lan != totalt_antal_roster |
      giltiga_roster_lan != giltiga_roster |
      ogiltiga_roster_lan != ogiltiga_roster
  )

kontroll_riket
```

```{r}
rf_files <- index_tbl |>
  filter(
    str_detect(
      path,
      "^p/rf/.*_[0-9]{2}_RF\\.zip$"
    )
  )

nrow(rf_files)

index_tbl |>
  filter(str_starts(path, "p/rf/")) |>
  pull(path)

rf_01 <- rf_files |>
  filter(str_detect(path, "_01_RF\\.zip$")) |>
  mutate(
    url = paste0(base_url, "/", path)
  )

system.time({
  valresultat_rf_01 <- read_rostfordelning_zip_2026(rf_01$url)
})


unique(valresultat_rf_01$valtyp)
unique(valresultat_rf_01$lankod)

n_distinct(valresultat_rf_01$valdistriktskod)

map_lgl(valresultat_rf_01, is.list) |>
  which()


kontroll_rf_01 <- valresultat_rf_01 |>
  summarise(
    partisumma = sum(antal_roster, na.rm = TRUE),
    giltiga_roster = first(giltiga_roster),
    totalt_antal_roster = first(totalt_antal_roster),
    ogiltiga_roster = first(ogiltiga_roster),
    summa_ogiltiga =
      first(roster_ej_anmalt_deltagande) +
      first(blanka_roster) +
      first(ovriga_ogiltiga),
    .by = valdistriktskod
  )

kontroll_rf_01 |>
  filter(partisumma != giltiga_roster)

kontroll_rf_01 |>
  filter(totalt_antal_roster != giltiga_roster + ogiltiga_roster)

kontroll_rf_01 |>
  filter(ogiltiga_roster != summa_ogiltiga)

valresultat_rf_01 |>
  count(
    valdistriktskod,
    partikod,
    ovriga_partier
  ) |>
  filter(n > 1)

rf_files <- rf_files |>
  mutate(
    url = paste0(base_url, "/", path)
  )

system.time({
  valresultat_rf <- rf_files$url |>
    map(read_kf_file, .progress = TRUE) |>
    list_rbind()
})
```


```{r}
source("R/utils.R")
source("R/parse_index_2026.R")
source("R/parse_rostfordelning_2026.R")
source("R/read_rostfordelning_2026.R")
source("R/parse_valdistriktskoppling_2026.R")
source("R/parse_summering_kf_2026.R")



```

```{r}
rf_files <- index_tbl |>
  filter(
    str_detect(
      path,
      "^p/rf/.*_[0-9]{2}_RF\\.zip$"
    )
  ) |>
  mutate(
    url = paste0(base_url, "/", path)
  )

system.time({
  valresultat_rf <- rf_files$url |>
    map(read_rostfordelning_zip_2026, .progress = TRUE) |>
    list_rbind()
})


n_distinct(valresultat_rf$lankod)
unique(valresultat_rf$valtyp)

map_lgl(valresultat_rf, is.list) |>
  which()

valresultat_rf |>
  count(
    lankod,
    valdistriktskod,
    partikod,
    ovriga_partier
  ) |>
  filter(n > 1)

kontroll_rf <- valresultat_rf |>
  summarise(
    partisumma = sum(antal_roster, na.rm = TRUE),
    giltiga_roster = first(giltiga_roster),
    totalt_antal_roster = first(totalt_antal_roster),
    ogiltiga_roster = first(ogiltiga_roster),
    summa_ogiltiga =
      first(roster_ej_anmalt_deltagande) +
      first(blanka_roster) +
      first(ovriga_ogiltiga),
    .by = c(lankod, valdistriktskod)
  )

kontroll_rf |>
  filter(partisumma != giltiga_roster)

kontroll_rf |>
  filter(totalt_antal_roster != giltiga_roster + ogiltiga_roster)

kontroll_rf |>
  filter(ogiltiga_roster != summa_ogiltiga)
```

```{r}
os_rf_file <- index_tbl |>
  filter(str_detect(path, "^p/rf/.*_OS_RF\\.zip$"))

os_rf_file

rf_01_zip <- tempfile(fileext = ".zip")

download.file(
  rf_01$url,
  rf_01_zip,
  mode = "wb"
)

unzip(rf_01_zip, list = TRUE)
```

```{r}
source("R/utils.R")
source("R/parse_summering_rd_rf_2026.R")
source("R/read_summering_2026.R")

valresultat_rf_kommun <- read_summering_zip_2026(rf_01$url)

valresultat_rf_kommun |>
  distinct(geografiniva, lankod, kommunkod, kommunvalkretskod) |>
  count(geografiniva)

valresultat_rf_kommun |>
  filter(geografiniva == "kommunvalkrets") |>
  distinct(
    kommunnamn,
    kommunkod,
    kommunvalkretsnamn,
    kommunvalkretskod
  ) |>
  arrange(kommunkod, kommunvalkretskod)

rf_fran_valdistrikt <- valresultat_rf_01 |>
  summarise(
    antal_roster_valdistrikt = sum(antal_roster),
    .by = c(kommunkod, partikod, ovriga_partier)
  )

kontroll_rf_kommun <- valresultat_rf_kommun |>
  filter(geografiniva == "kommun") |>
  select(
    kommunkod,
    partikod,
    ovriga_partier,
    antal_roster
  ) |>
  left_join(
    rf_fran_valdistrikt,
    by = join_by(
      kommunkod,
      partikod,
      ovriga_partier
    )
  ) |>
  filter(
    antal_roster != antal_roster_valdistrikt |
      is.na(antal_roster_valdistrikt)
  )

kontroll_rf_kommun
```


```{r}
system.time({
  valresultat_rf_under <- rf_files$url |>
    map(read_summering_zip_2026, .progress = TRUE) |>
    list_rbind()
})

valresultat_rf_under |>
  filter(geografiniva == "kommun") |>
  summarise(
    antal_regioner = n_distinct(lankod),
    antal_kommuner = n_distinct(kommunkod)
  )


rf_fran_valdistrikt <- valresultat_rf |>
  summarise(
    antal_roster_valdistrikt = sum(antal_roster),
    .by = c(lankod, kommunkod, partikod, ovriga_partier)
  )

kontroll_rf_kommun <- valresultat_rf_under |>
  filter(geografiniva == "kommun") |>
  select(
    lankod,
    kommunkod,
    partikod,
    ovriga_partier,
    antal_roster
  ) |>
  left_join(
    rf_fran_valdistrikt,
    by = join_by(
      lankod,
      kommunkod,
      partikod,
      ovriga_partier
    )
  ) |>
  filter(
    antal_roster != antal_roster_valdistrikt |
      is.na(antal_roster_valdistrikt)
  )

kontroll_rf_kommun

rf_fran_valdistrikt |>
  anti_join(
    valresultat_rf_under |>
      filter(geografiniva == "kommun"),
    by = join_by(
      lankod,
      kommunkod,
      partikod,
      ovriga_partier
    )
  )
```


```{r}
os_rf_file <- index_tbl |>
  filter(str_detect(path, "^p/rf/.*_OS_RF\\.zip$"))

os_rf_file

os_rf_url <- paste0(base_url, "/", os_rf_file$path)

os_rf_zip <- tempfile(fileext = ".zip")
download.file(os_rf_url, os_rf_zip, mode = "wb")

unzip(os_rf_zip, list = TRUE)

os_rf_files <- unzip(os_rf_zip, list = TRUE)

os_rf_json <- os_rf_files$Name |>
  str_subset("\\.json$")

os_rf_dir <- tempfile()
dir.create(os_rf_dir)

unzip(
  os_rf_zip,
  files = os_rf_json,
  exdir = os_rf_dir
)

os_rf_raw <- fromJSON(
  file.path(os_rf_dir, os_rf_json),
  simplifyVector = FALSE
)

names(os_rf_raw$helaLandet)

length(os_rf_raw$helaLandet$lan)

names(os_rf_raw$helaLandet$lan[[1]])

```

```{r}
source("R/parse_overordnad_summering_rf_2026.R")

valresultat_rf_over <-
  parse_overordnad_summering_rf_2026(os_rf_raw)


valresultat_rf_over |>
  distinct(geografiniva, lankod) |>
  count(geografiniva)

map_lgl(valresultat_rf_over, is.list) |>
  which()

rf_kommun_tot <- valresultat_rf_under |>
  filter(geografiniva == "kommun") |>
  distinct(
    lankod,
    kommunkod,
    totalt_antal_roster,
    giltiga_roster,
    ogiltiga_roster
  )

kontroll_region <- rf_kommun_tot |>
  summarise(
    totalt_antal_roster_kommun = sum(totalt_antal_roster),
    giltiga_roster_kommun = sum(giltiga_roster),
    ogiltiga_roster_kommun = sum(ogiltiga_roster),
    .by = lankod
  ) |>
  left_join(
    valresultat_rf_over |>
      filter(geografiniva == "region") |>
      distinct(
        lankod,
        totalt_antal_roster,
        giltiga_roster,
        ogiltiga_roster
      ),
    by = join_by(lankod)
  ) |>
  filter(
    totalt_antal_roster_kommun != totalt_antal_roster |
      giltiga_roster_kommun != giltiga_roster |
      ogiltiga_roster_kommun != ogiltiga_roster
  )

kontroll_region

kontroll_riket_rf <- valresultat_rf_over |>
  filter(geografiniva == "region") |>
  distinct(
    lankod,
    totalt_antal_roster,
    giltiga_roster,
    ogiltiga_roster
  ) |>
  summarise(
    totalt_antal_roster_region = sum(totalt_antal_roster),
    giltiga_roster_region = sum(giltiga_roster),
    ogiltiga_roster_region = sum(ogiltiga_roster)
  ) |>
  cross_join(
    valresultat_rf_over |>
      filter(geografiniva == "riket") |>
      distinct(
        totalt_antal_roster,
        giltiga_roster,
        ogiltiga_roster
      )
  ) |>
  filter(
    totalt_antal_roster_region != totalt_antal_roster |
      giltiga_roster_region != giltiga_roster |
      ogiltiga_roster_region != ogiltiga_roster
  )

kontroll_riket_rf

```

```{r}
source("R/utils.R")
source("R/parse_rostfordelning_2026.R")
source("R/read_rostfordelning_2026.R")
source("R/parse_underordnad_summering_2026.R")
source("R/read_underordnad_summering_2026.R")

valresultat_rd <-
  read_rostfordelning_zip_2026(rd_url)

valresultat_rd_under <-
  read_underordnad_summering_zip_2026(rd_url)
```

```{r}
valresultat_rd_under |>
  distinct(
    geografiniva,
    lankod,
    kommunkod,
    kommunvalkretskod
  ) |>
  count(geografiniva)

rd_fran_valdistrikt <- valresultat_rd |>
  summarise(
    antal_roster_valdistrikt = sum(antal_roster),
    .by = c(
      kommunkod,
      partikod,
      ovriga_partier
    )
  )

kontroll_rd_kommun <- valresultat_rd_under |>
  filter(geografiniva == "kommun") |>
  select(
    kommunkod,
    partikod,
    ovriga_partier,
    antal_roster
  ) |>
  left_join(
    rd_fran_valdistrikt,
    by = join_by(
      kommunkod,
      partikod,
      ovriga_partier
    )
  ) |>
  filter(
    antal_roster != antal_roster_valdistrikt |
      is.na(antal_roster_valdistrikt)
  )

kontroll_rd_kommun

rd_fran_valdistrikt |>
  anti_join(
    valresultat_rd_under |>
      filter(geografiniva == "kommun"),
    by = join_by(
      kommunkod,
      partikod,
      ovriga_partier
    )
  )

```

# Mandat

```{r}
rd_files <- unzip(rd_zip, list = TRUE)

rd_mandat_file <- rd_files$Name |>
  str_subset("mandatfordelning.*00_RD\\.json$")

rd_mandat_file

rd_mandat_dir <- tempfile()
dir.create(rd_mandat_dir)

unzip(
  rd_zip,
  files = rd_mandat_file,
  exdir = rd_mandat_dir
)

rd_mandat_raw <- fromJSON(
  file.path(rd_mandat_dir, rd_mandat_file),
  simplifyVector = FALSE
)

names(rd_mandat_raw)

names(rd_mandat_raw$valomrade)

length(rd_mandat_raw$valomrade$valkretsLista)

names(rd_mandat_raw$valomrade$valkretsLista[[1]])

names(rd_mandat_raw$valomrade$mandatfordelning)

str(
  rd_mandat_raw$valomrade$mandatfordelning$partiLista,
  max.level = 2
)

```

```{r}
names(
  rd_mandat_raw$valomrade$valkretsLista[[1]]$
    mandatfordelning$partiLista[[1]]
)
names(
  rd_mandat_raw$valomrade$valkretsLista[[1]]$
    rostfordelning$rosterPaverkaMandat$partiRoster[[1]]
)

```


```{r}
source("R/parse_rostfordelning_mandat_2026.R")
source("R/parse_mandat_2026.R")

valresultat_rd_over <-
  parse_rostfordelning_mandat_2026(rd_mandat_raw)

mandat_rd <-
  parse_mandat_2026(rd_mandat_raw)


valresultat_rd_over |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

mandat_rd |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

map_lgl(valresultat_rd_over, is.list) |> which()
map_lgl(mandat_rd, is.list) |> which()

kontroll_rd_riket <- valresultat_rd_over |>
  filter(geografiniva == "riksdagsvalkrets") |>
  distinct(
    valkrets_kod,
    totalt_antal_roster,
    giltiga_roster,
    ogiltiga_roster
  ) |>
  summarise(
    totalt_antal_roster_valkrets = sum(totalt_antal_roster),
    giltiga_roster_valkrets = sum(giltiga_roster),
    ogiltiga_roster_valkrets = sum(ogiltiga_roster)
  ) |>
  cross_join(
    valresultat_rd_over |>
      filter(geografiniva == "riket") |>
      distinct(
        totalt_antal_roster,
        giltiga_roster,
        ogiltiga_roster
      )
  ) |>
  filter(
    totalt_antal_roster_valkrets != totalt_antal_roster |
      giltiga_roster_valkrets != giltiga_roster |
      ogiltiga_roster_valkrets != ogiltiga_roster
  )

kontroll_rd_riket

valresultat_rd_over |>
  filter(!ovriga_partier) |>
  count(geografiniva, over_sparr)


mandat_rd |>
  filter(geografiniva == "riket") |>
  summarise(
    summa_mandat = sum(antal_mandat),
    summa_fasta = sum(antal_fasta_mandat),
    summa_utjamning = sum(antal_utjamningsmandat),
    totalt_antal_mandat = first(totalt_antal_mandat),
    totalt_antal_fasta = first(totalt_antal_fasta_mandat),
    totalt_antal_utjamning = first(totalt_antal_utjamningsmandat)
  )

mandat_rd |>
  summarise(
    summa_mandat = sum(antal_mandat, na.rm = TRUE),
    totalt_antal_mandat = first(totalt_antal_mandat),
    .by = c(geografiniva, valkrets_kod)
  ) |>
  filter(summa_mandat != totalt_antal_mandat)


rd_mandat_raw$valomrade$rostfordelning$
  rosterPaverkaMandat$partiRoster |>
  map_chr(\(x) as_chr_na(x$deltaMandatfordelning))

rd_mandat_raw$valomrade$valkretsLista[[1]]$rostfordelning$
  rosterPaverkaMandat$partiRoster |>
  map_chr(\(x) as_chr_na(x$deltaMandatfordelning))

source("R/parse_rostfordelning_mandat_2026.R")

valresultat_rd_over <-
  parse_rostfordelning_mandat_2026(rd_mandat_raw)

valresultat_rd_over |>
  filter(!ovriga_partier) |>
  count(geografiniva, over_sparr)
```


```{r}
mandat_rd |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

map_lgl(mandat_rd, is.list) |>
  which()

mandat_rd |>
  filter(
    antal_mandat != antal_fasta_mandat + antal_utjamningsmandat
  )

mandat_rd |>
  filter(geografiniva == "riket") |>
  summarise(
    summa_mandat = sum(antal_mandat),
    summa_fasta = sum(antal_fasta_mandat),
    summa_utjamning = sum(antal_utjamningsmandat),
    totalt_mandat = first(totalt_antal_mandat),
    totalt_fasta = first(totalt_antal_fasta_mandat),
    totalt_utjamning = first(totalt_antal_utjamningsmandat)
  )

mandat_rd |>
  filter(geografiniva == "riksdagsvalkrets") |>
  summarise(
    summa_mandat = sum(antal_mandat),
    summa_fasta = sum(antal_fasta_mandat),
    summa_utjamning = sum(antal_utjamningsmandat),
    totalt_mandat = first(totalt_antal_mandat),
    totalt_fasta = first(totalt_antal_fasta_mandat),
    totalt_utjamning = first(totalt_antal_utjamningsmandat),
    .by = c(valkrets_kod, valkrets_namn)
  ) |>
  filter(
    summa_mandat != totalt_mandat |
      summa_fasta != totalt_fasta |
      summa_utjamning != totalt_utjamning
  )

```


```{r}
rf_01_files <- unzip(rf_01_zip, list = TRUE)

rf_01_mandat_file <- rf_01_files$Name |>
  str_subset("mandatfordelning.*01_RF\\.json$")

rf_01_mandat_dir <- tempfile()
dir.create(rf_01_mandat_dir)

unzip(
  rf_01_zip,
  files = rf_01_mandat_file,
  exdir = rf_01_mandat_dir
)

rf_01_mandat_raw <- fromJSON(
  file.path(rf_01_mandat_dir, rf_01_mandat_file),
  simplifyVector = FALSE
)

valresultat_rf_over_01 <-
  parse_rostfordelning_mandat_2026(rf_01_mandat_raw)

mandat_rf_01 <-
  parse_mandat_2026(rf_01_mandat_raw)

valresultat_rf_over_01 |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

mandat_rf_01 |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

map_lgl(valresultat_rf_over_01, is.list) |> which()
map_lgl(mandat_rf_01, is.list) |> which()

valresultat_rf_over_01 |>
  filter(!ovriga_partier) |>
  count(geografiniva, over_sparr)

mandat_rf_01 |>
  filter(
    antal_mandat != antal_fasta_mandat + antal_utjamningsmandat
  )

kontroll_rf_roster <- valresultat_rf_over_01 |>
  filter(geografiniva == "regionvalkrets") |>
  distinct(
    valkrets_kod,
    totalt_antal_roster,
    giltiga_roster,
    ogiltiga_roster
  ) |>
  summarise(
    totalt_antal_roster_valkrets = sum(totalt_antal_roster),
    giltiga_roster_valkrets = sum(giltiga_roster),
    ogiltiga_roster_valkrets = sum(ogiltiga_roster)
  ) |>
  cross_join(
    valresultat_rf_over_01 |>
      filter(geografiniva == "region") |>
      distinct(
        totalt_antal_roster,
        giltiga_roster,
        ogiltiga_roster
      )
  ) |>
  filter(
    totalt_antal_roster_valkrets != totalt_antal_roster |
      giltiga_roster_valkrets != giltiga_roster |
      ogiltiga_roster_valkrets != ogiltiga_roster
  )

kontroll_rf_roster

kontroll_rf_mandat <- mandat_rf_01 |>
  filter(geografiniva == "regionvalkrets") |>
  summarise(
    antal_mandat_valkrets = sum(antal_mandat),
    antal_fasta_mandat_valkrets = sum(antal_fasta_mandat),
    antal_utjamningsmandat_valkrets = sum(antal_utjamningsmandat),
    .by = c(partikod, partibeteckning)
  ) |>
  left_join(
    mandat_rf_01 |>
      filter(geografiniva == "region") |>
      select(
        partikod,
        antal_mandat,
        antal_fasta_mandat,
        antal_utjamningsmandat
      ),
    by = join_by(partikod)
  ) |>
  filter(
    antal_mandat_valkrets != antal_mandat |
      antal_fasta_mandat_valkrets != antal_fasta_mandat |
      antal_utjamningsmandat_valkrets != antal_utjamningsmandat
  )

kontroll_rf_mandat

```


```{r}
read_mandat_zip_2026 <- function(zip_file) {

  source <- zip_file

  tryCatch(
    {
      is_url <- grepl("^https?://", zip_file)

      if (is_url) {
        tmp_zip <- tempfile(fileext = ".zip")
        utils::download.file(
          zip_file,
          tmp_zip,
          mode = "wb",
          quiet = TRUE
        )
        zip_file <- tmp_zip
        on.exit(unlink(tmp_zip), add = TRUE)
      }

      files <- utils::unzip(zip_file, list = TRUE)

      mandat_file <- files$Name |>
        stringr::str_subset("mandatfordelning.*\\.json$")

      if (length(mandat_file) != 1) {
        stop(
          "Förväntade mig exakt en mandatfördelningsfil i ZIP-filen, men hittade ",
          length(mandat_file),
          ".",
          call. = FALSE
        )
      }

      tmp_dir <- tempfile()
      dir.create(tmp_dir)
      on.exit(unlink(tmp_dir, recursive = TRUE), add = TRUE)

      utils::unzip(
        zip_file,
        files = mandat_file,
        exdir = tmp_dir
      )

      raw <- jsonlite::fromJSON(
        file.path(tmp_dir, mandat_file),
        simplifyVector = FALSE
      )

      list(
        valresultat = parse_rostfordelning_mandat_2026(raw),
        mandat = parse_mandat_2026(raw)
      )
    },
    error = \(e) {
      stop(
        "Fel vid läsning av:\n",
        source,
        "\n\n",
        conditionMessage(e),
        call. = FALSE
      )
    }
  )
}

rf_01_mandat <- read_mandat_zip_2026(rf_01$url)

rf_01_mandat$valresultat
rf_01_mandat$mandat

rf_mandat_all <- rf_files$url |>
  map(read_mandat_zip_2026, .progress = TRUE)

valresultat_rf_mandat <- rf_mandat_all |>
  map("valresultat") |>
  list_rbind()

mandat_rf <- rf_mandat_all |>
  map("mandat") |>
  list_rbind()


mandat_rf |>
  distinct(
    valomradeskod,
    geografiniva,
    valkrets_kod
  ) |>
  count(geografiniva)

n_distinct(
  mandat_rf$valomradeskod[
    mandat_rf$geografiniva == "region"
  ]
)

map_lgl(mandat_rf, is.list) |>
  which()

rf_mandat_fran_valkrets <- mandat_rf |>
  filter(geografiniva == "regionvalkrets") |>
  summarise(
    antal_mandat_valkrets = sum(antal_mandat),
    antal_fasta_mandat_valkrets = sum(antal_fasta_mandat),
    antal_utjamningsmandat_valkrets = sum(antal_utjamningsmandat),
    .by = c(
      valomradeskod,
      partikod
    )
  )

kontroll_rf_mandat <- mandat_rf |>
  filter(geografiniva == "region") |>
  select(
    valomradeskod,
    partikod,
    antal_mandat,
    antal_fasta_mandat,
    antal_utjamningsmandat
  ) |>
  left_join(
    rf_mandat_fran_valkrets,
    by = join_by(
      valomradeskod,
      partikod
    )
  ) |>
  filter(
    antal_mandat != antal_mandat_valkrets |
      antal_fasta_mandat != antal_fasta_mandat_valkrets |
      antal_utjamningsmandat != antal_utjamningsmandat_valkrets
  )

kontroll_rf_mandat

```

## Kommunmandat

```{r}
kf_0180_mandat <- read_mandat_zip_2026(kf_0180_url)

valresultat_kf_mandat_0180 <- kf_0180_mandat$valresultat
mandat_kf_0180 <- kf_0180_mandat$mandat

valresultat_kf_mandat_0180 |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

mandat_kf_0180 |>
  distinct(geografiniva, valkrets_kod) |>
  count(geografiniva)

map_lgl(valresultat_kf_mandat_0180, is.list) |> which()
map_lgl(mandat_kf_0180, is.list) |> which()

valresultat_kf_mandat_0180 |>
  filter(!ovriga_partier) |>
  count(geografiniva, over_sparr)

mandat_kf_0180 |>
  filter(
    antal_mandat != antal_fasta_mandat + antal_utjamningsmandat
  )

kontroll_kf_mandat <- mandat_kf_0180 |>
  filter(geografiniva == "kommunvalkrets") |>
  summarise(
    antal_mandat_valkrets = sum(antal_mandat),
    antal_fasta_mandat_valkrets = sum(antal_fasta_mandat),
    antal_utjamningsmandat_valkrets = sum(antal_utjamningsmandat),
    .by = partikod
  ) |>
  left_join(
    mandat_kf_0180 |>
      filter(geografiniva == "kommun") |>
      select(
        partikod,
        antal_mandat,
        antal_fasta_mandat,
        antal_utjamningsmandat
      ),
    by = join_by(partikod)
  ) |>
  filter(
    antal_mandat_valkrets != antal_mandat |
      antal_fasta_mandat_valkrets != antal_fasta_mandat |
      antal_utjamningsmandat_valkrets != antal_utjamningsmandat
  )

kontroll_kf_mandat

kf_0180_mandat_file <- unzip(kf_0180_zip, list = TRUE)$Name |>
  str_subset("mandatfordelning.*0180_KF\\.json$")

kf_0180_mandat_dir <- tempfile()
dir.create(kf_0180_mandat_dir)

unzip(
  kf_0180_zip,
  files = kf_0180_mandat_file,
  exdir = kf_0180_mandat_dir
)

kf_0180_mandat_raw <- fromJSON(
  file.path(kf_0180_mandat_dir, kf_0180_mandat_file),
  simplifyVector = FALSE
)

kf_0180_mandat_raw$valomrade$valomradessparrProcent
kf_0180_mandat_raw$valomrade$valkretssparrProcent

kf_0180_mandat_raw$valomrade$rostfordelning$
  rosterPaverkaMandat$partiRoster |>
  map_dfr(\(x) tibble(
    parti = x$partiforkortning,
    andel = x$andelRoster,
    delta = x$deltaMandatfordelning
  ))

```

```{r}
kf_mandat_all <- kf_files$url |>
  map(read_mandat_zip_2026, .progress = TRUE)

valresultat_kf_mandat <- kf_mandat_all |>
  map("valresultat") |>
  list_rbind()

mandat_kf <- kf_mandat_all |>
  map("mandat") |>
  list_rbind()

mandat_kf |>
  distinct(
    valomradeskod,
    geografiniva,
    valkrets_kod
  ) |>
  count(geografiniva)

n_distinct(
  mandat_kf$valomradeskod[
    mandat_kf$geografiniva == "kommun"
  ]
)

map_lgl(mandat_kf, is.list) |>
  which()

valresultat_kf_mandat |>
  filter(
    geografiniva == "kommun",
    !ovriga_partier
  ) |>
  count(over_sparr)


valkretskommuner <- mandat_kf |>
  filter(geografiniva == "kommunvalkrets") |>
  distinct(valomradeskod)

kf_mandat_fran_valkrets <- mandat_kf |>
  filter(geografiniva == "kommunvalkrets") |>
  summarise(
    antal_mandat_valkrets = sum(antal_mandat),
    antal_fasta_mandat_valkrets = sum(antal_fasta_mandat),
    antal_utjamningsmandat_valkrets = sum(antal_utjamningsmandat),
    .by = c(valomradeskod, partikod)
  )

kontroll_kf_mandat <- mandat_kf |>
  filter(geografiniva == "kommun") |>
  semi_join(
    valkretskommuner,
    by = join_by(valomradeskod)
  ) |>
  select(
    valomradeskod,
    partikod,
    antal_mandat,
    antal_fasta_mandat,
    antal_utjamningsmandat
  ) |>
  left_join(
    kf_mandat_fran_valkrets,
    by = join_by(valomradeskod, partikod)
  ) |>
  filter(
    antal_mandat != antal_mandat_valkrets |
      antal_fasta_mandat != antal_fasta_mandat_valkrets |
      antal_utjamningsmandat != antal_utjamningsmandat_valkrets
  )

kontroll_kf_mandat
```

# slutlig räkning

```{r}
rd_slutlig_file <- index_tbl |>
  filter(str_detect(path, "^s/rd/.*_00_RD\\.zip$")) |>
  mutate(url = paste0(base_url, "/", path))

rd_slutlig_file

valresultat_rd_slutlig <-
  read_rostfordelning_zip_2026(rd_slutlig_file$url)

rd_mandat_slutlig <-
  read_mandat_zip_2026(rd_slutlig_file$url)

valresultat_rd_mandat_slutlig <-
  rd_mandat_slutlig$valresultat

mandat_rd_slutlig <-
  rd_mandat_slutlig$mandat

unique(valresultat_rd_slutlig$rakningstillfalle)

valresultat_rd_slutlig |>
  distinct(geografiniva) 

valresultat_rd_mandat_slutlig |>
  distinct(geografiniva)

mandat_rd_slutlig |>
  distinct(geografiniva)

map_lgl(valresultat_rd_slutlig, is.list) |> which()
map_lgl(valresultat_rd_mandat_slutlig, is.list) |> which()
map_lgl(mandat_rd_slutlig, is.list) |> which()

identical(
  names(valresultat_rd),
  names(valresultat_rd_slutlig)
)

identical(
  names(valresultat_rd_over),
  names(valresultat_rd_mandat_slutlig)
)

identical(
  names(mandat_rd),
  names(mandat_rd_slutlig)
)
```

```{r}
rd_slutlig_zip <- tempfile(fileext = ".zip")

download.file(
  rd_slutlig_file$url,
  rd_slutlig_zip,
  mode = "wb"
)

rd_slutlig_json <- unzip(rd_slutlig_zip, list = TRUE)$Name |>
  str_subset("rostfordelning.*00_RD\\.json$")

rd_slutlig_dir <- tempfile()
dir.create(rd_slutlig_dir)

unzip(
  rd_slutlig_zip,
  files = rd_slutlig_json,
  exdir = rd_slutlig_dir
)

rd_slutlig_raw <- fromJSON(
  file.path(rd_slutlig_dir, rd_slutlig_json),
  simplifyVector = FALSE
)

parti_med_listor <- rd_slutlig_raw$valdistrikt |>
  map(\(vd) {
    vd$rostfordelning$rosterPaverkaMandat$partiRoster |>
      keep(\(p) length(p$listRoster) > 0) |>
      first()
  }) |>
  compact() |>
  first()

names(parti_med_listor$listRoster[[1]])
names(parti_med_listor$listRoster[[1]]$personroster[[1]])
names(parti_med_listor$summeradePersonroster[[1]])

```



```{r}
source("R/parse_personroster_2026.R")

persondata_rd <- parse_personroster_2026(rd_slutlig_raw)

persondata_rd$listroster
persondata_rd$personroster
persondata_rd$personroster_summerade

map(persondata_rd, dim)

map(persondata_rd, \(x) map_lgl(x, is.list) |> which())

kontroll_listor <- persondata_rd$personroster |>
  summarise(
    summa_personroster = sum(antal_personroster),
    antal_roster_med_personrost = first(antal_roster_med_personrost),
    .by = c(
      valdistriktskod,
      partikod,
      listnummer
    )
  ) |>
  filter(summa_personroster != antal_roster_med_personrost)

kontroll_listor

person_sum <- persondata_rd$personroster |>
  summarise(
    antal_personroster_listor = sum(antal_personroster),
    .by = c(
      valdistriktskod,
      partikod,
      kandidatnummer
    )
  )

kontroll_person <- persondata_rd$personroster_summerade |>
  select(
    valdistriktskod,
    partikod,
    kandidatnummer,
    antal_personroster
  ) |>
  left_join(
    person_sum,
    by = join_by(
      valdistriktskod,
      partikod,
      kandidatnummer
    )
  ) |>
  filter(
    antal_personroster != antal_personroster_listor |
      is.na(antal_personroster_listor)
  )

kontroll_person


```

